export const POINT_RULES = {
  ASSIGNMENT_SUBMISSION: 20,
  ASSIGNMENT_GRADED_BONUS: 30, // awarded based on high marks
  QUIZ_COMPLETED_BASE: 15,
  QUIZ_PERFECT_SCORE: 50,
  DAILY_CHALLENGE: 25,
  WEEKLY_CHALLENGE: 75,
  MONTHLY_CHALLENGE: 200,
  FORUM_QUESTION_POSTED: 5,
  FORUM_ANSWER_POSTED: 10,
  FORUM_ANSWER_ACCEPTED: 40,
  FORUM_ANSWER_UPVOTED: 5,
  STREAK_7_DAYS: 50,
} as const;

export type PointSourceType =
  | 'ASSIGNMENT'
  | 'QUIZ'
  | 'CHALLENGE'
  | 'FORUM_POST'
  | 'FORUM_ANSWER'
  | 'FORUM_ACCEPTED'
  | 'FORUM_UPVOTE'
  | 'STREAK_BONUS'
  | 'ADMIN_GRANT';
